### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by rwbc** [mhouppin/vault#1]
Hi Morgan, after I saw your first beta release I tried building it for WIN here myself..
But what ever build I try I always get this error below in the end.

Also I see no path to the eval file at all in the makefile, but I did not check if one of the network source files
contains the path to it...

```
cc -Wall -Wextra -Wcast-qual -Wshadow -Werror -O3 -flto -DUSE_PREFETCH -m64 -msse -msse2 -msse -msse2 -mssse3 -o vault.exe sources/accumulator.o sources/activation.o sources/bench.o sources/bitboard.o sources/board.o sources/dataset.o sources/endgame.o sources/evaluate.o sources/hashkey.o sources/history.o sources/kpk_bitbase.o sources/main.o sources/matrix.o sources/movelist.o sources/movepick.o sources/network.o sources/option.o sources/pawns.o sources/psq_score.o sources/search.o sources/timeman.o sources/training.o sources/tt.o sources/uci.o sources/weight.o sources/worker.o -lpthread -lm
sources/network.c: In function 'nn_create.constprop':
sources/network.c:124:13: error: 'MEM[(int *)_6]' may be used uninitialized [-Werror=maybe-uninitialized]
  124 |             fprintf(stderr, "nn_create(): Activation id %d doesn't exist\n", nn->activationIds[i]);
      |             ^
lto1.exe: all warnings being treated as errors
lto-wrapper.exe: fatal error: C:\msys64\mingw64\bin\cc.exe returned 1 exit status
```

**Comment by rwbc** [comment]
As expected I can build a working binary w/o the flto flag, haven't checked the speed yet compared to your binaries.

**Edit:**
I get this extra message then in the beginning (and a somehow 7-9% slower binary compared to yours for my hardware)
```
nn_load(".gitattributes"): Unable to allocate layer size data: Not enough space
nn_load(".gitignore"): Unable to allocate activation function data: Not enough space
...
```

**Comment by mhouppin** [comment]
The extra message is "normal" (in the sense that it's looking for files which do not contain a network, and throws an error when it fails to load them), as well as the slowdown by disabling `-flto` (which is probably related to the accumulator functions not being inlined). I'll fix the compilation error and disable the error messages by not trying to autoload files that have no `.nn` extension.

**Comment by mhouppin** [comment]
I pushed the fix on https://github.com/mhouppin/vault/tree/fix_autoload_errors, can you verify that the engines compiles correctly on this branch with LTO enabled and that no spurious error messages appear at startup ?

**Comment by rwbc** [comment]
> I pushed the fix on https://github.com/mhouppin/vault/tree/fix_autoload_errors, can you verify that the engines compiles correctly on this branch with LTO enabled and that no spurious error messages appear at startup ?

=> confirmed to be building w/o error message with LTO as Vault 0.41 and also w/o error message at startup :)

**Comment by mhouppin** [comment]
Perfect, I'll merge this, thanks for the report ^^
